[package]
name = "mmsb-intent"
version = "0.1.0"
edition = "2024"

[dependencies]
mmsb-proof = { path = "../mmsb-proof" }
mmsb-service = { path = "../mmsb-service" }
serde = { version = "1.0", features = ["derive"] }
