[package]
name = "mmsb-propagation"
version = "0.1.0"
edition = "2021"

[lib]
name = "mmsb_propagation"
path = "src/lib.rs"

[dependencies]
mmsb-primitives = { path = "../mmsb-primitives" }
mmsb-physical = { path = "../mmsb-physical" }
parking_lot = "0.12"
