name = "MMSB"
uuid = "8e464427-1522-4382-b3ea-4966b903a233"
version = "0.1.0-alpha"
authors = ["Cicero Bugash <cicero.bugash@gmail.com>"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CUDA = "5.9.5"
Logging = "1.11.0"
Lux = "1.27.1"
Optimisers = "0.4.6"
Serialization = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
