[package]
name = "mmsb-executor"
version = "0.1.0"
edition = "2021"

[lib]
name = "mmsb_executor"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

mmsb-proof = { path = "../mmsb-proof" }
mmsb-events = { path = "../mmsb-events" }
